const mongoose=require('mongoose');

const profileschema=new mongoose.Schema({
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        unique:true
    },
    familyBackground:{
        fatherStatus:{
            type:String
        },
        motherStatus:{
            type:String
        }
    },
    Interests:{
        type:Array,
    },
    Hobbies:{
        type:Array
    },
    location:{
        city:{
            type:String
        },
        country:{
            type:String
        },
        address:{
            type:String
        }
    },
    photos:{
        type:Array
    },
    religon:{
        type:String
    },
    education:{
        type:String
    },
    profession:{
        type:String
    },
    nationality:{
        type:String
    },
    description:{
        type:String
    },
    Age:Number,
    Siblings:Number,
    height:{
        type:String
    },
    bodyWeight:{
        type:String
    },
    complexion:{
        type:String
    },
})
module.exports=mongoose.model("profile",profileschema);